   const Data =  {
        Plantsome: {
           name: "Plantsome",
           desc: "Simpelweg planten.",
           imgSrc: "https://images.unsplash.com/photo-1517204452548-5f07ce910c9b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
           timeFrame: "2017 - Nu",
           workDone: "Concept & Design",
           website: "https://plantsome.nl",
           intro: "Plantsome.nl is dé webshop die het kopen van kamerplanten leuker en makkelijker maakt. Bij Keytoe ben ik al 4 jaar betrokken als UX Designer voor Plantsome. Vanaf het digitaal vertalen van de re-branding in 2018 tot doorlopende conversie optimalisatie en ontwerpen van een CMS en Design System. ",
           img_1: "/images/plantsome_1.png",
           title_1: "Research",
           txt_1: "Om inzicht te krijgen in de behoefte van de doelgroep heb ik tientallen diepte-interviews gedaan met hele diverse groepen, van studenten tot 50-plussers, met als doel om te achterhalen waarom zij kamerplanten kopen en wat ze nou echt belangrijk vinden aan het (online) kopen van kamerplanten. De belangrijkste inzichten? “Wat een vreemde namen”, “Hoe groot is die plant nou echt?”, “Hoe verzorg ik zo’n plant?” en “Hoe weet ik nou welke plant ik nodig heb?” ",
           img_2: "/images/plantsome_2.png",
           title_2: "Redesign & CRO",
           txt_2: "Het was duidelijk dat Plantsome een merk moest gaan worden. Bij Keytoe waren mijn collega’s betrokken bij het maken van de brand-identity, de copy en development. Ik was verantwoordelijk voor de vertaling van de BI naar de webshop. Het doel: een zo hoog mogelijke conversie en het merk Plantsome een digitaal gezicht geven.",
           img_3: "/images/plantsome_3.png",
           title_3: "Zoeken & filteren",
           txt_3: "Filteren is voor Plantsome een enorm belangrijk onderdeel van de website. Het filter zou gaan moeten dienen als makkelijke manier om de juiste plant te vinden, maar de gebruiker ook direct te leren dat een plant bijvoorbeeld giftig kan zijn en welke standplaats nou belangrijk is. Om het filteren dus intuïtief en leerzaam tegelijk te maken bedacht ik de ‘zin-filter’. Je vult de zin in en wordt aan de hand genomen richting je nieuwe groene vriend. ",
           img_4: "/images/Plantsome_4.png",
           title_4: "Plantsome Dashboard",
           txt_4: "De pakketten van Plantsome is database-technisch een vrij ingewikkeld product. Met verschillende producten binnen een product en daarbij weer verschillende potten die je moet kiezen liepen we hier in het huidige CMS tegen behoorlijke obstakels aan. Het was aan mij om te zorgen voor een nieuw ontwerp van het CMS, wat snel geïmplementeerd kon worden en perfect op de behoefte van de gebruiker aansloot. Ik heb dat gedaan met behulp van user-testing en de verbinding maken tussen de verschillende stakeholders.",
           img_5: "/images/Plantsome_5.png",

        },
        Rumag: {
         name: "RUMAG",
         desc: "Business platform",
         imgSrc: "/images/rumag_1.jpg",
         timeFrame: "2020 - 2021",
         workDone: "Concept & Design",
         website: "https://rumag.nl",
         intro: "RUMAG is een platform met meer dan 2,4 miljoen volgers met een doelgroep die voor veel marketeers enorm lastig is om aan te spreken. Ik mocht met Keytoe aan de slag om een platform in te richten waar RUMAG zich als mediabureau neerzet om partners aan te trekken.",
         img_1: "/images/rumag_2.png",
         title_1: "Research",
         txt_1: "Om te achterhalen wat marketeers belangrijk vinden aan een platform als RUMAG was mijn eerste taak om dit te onderzoeken bij de huidige klanten. De belangrijkste inzichten waren de unieke doelgroep, daadkrachtige samenwerking en positieve resultaten. Deze kernpunten waren voor ons essentieel om te verwerken in de pagina’s.",
         img_2: "/images/rumag_3.png",
         title_2: "Concept & Design",
         txt_2: "Om de user experience optimaal te laten zijn was het voor mij belangrijk dat de bezoeker alle informatie op de juiste momenten op zijn bord kreeg. Daarnaast was het voor RUMAG belangrijk dat de ervaring zoals die op hun platform is ook doorvertaald zou worden in het ontwerp. ",
         img_3: "/images/rumag_4.png"
         },
         Sirelo: {
            name: "Sirelo",
            desc: "Verhuizen met een glimlach.",
            imgSrc: "/images/sirelo_1.jpeg",
            timeFrame: "2020 - Nu",
            workDone: "Concept & Design",
            website: "https://sirelo.nl",
            intro: "Sirelo is een internationaal verhuisplatform. Met maandelijks duizenden gebruikers over de hele wereld helpt Sirelo talloze gezinnen met verhuizen. Waar verhuizen een hoop stress oplevert, probeert Sirelo je het zo stressvrij mogelijk te maken. ",
            img_1: "/images/sirelo_2.png",
            title_1: "Klantvraag",
            txt_1: "Onderzoeken in de doelgroep vertelden mij dat verhuizen inderdaad een hoop stress oplevert, maar de boventoon voerde toch echt dat verhuizen naar het buitenland voor iedereen leuk en een waar avontuur is. En dat gevoel was precies wat Sirelo moest gaan uitstralen. De huidige branding kon dan ook een goede touch-up gebruiken.",
            img_2: "/images/sirelo_3.png",
            title_2: "Merkarchetype & digital design",
            txt_2: "Om Sirelo te positioneren kozen we ervoor om voor Sirelo een merkarchetype te bepalen. Dit archetype zorgt ervoor dat het merk gepersonifieerd wordt en daarmee tastbaarder wordt voor alle stakeholders om mee aan de slag te gaan. Door de omvang van het bedrijf was dit een oplossing voor een belangrijke uitdaging in de organisatie. Na onderzoek kwamen we erachter dat het merkarchetypen van Sirelo een 'Entertainende Wijze' zou moeten zijn. Precies zoals Freek Vonk en Neil deGrasse Tyson dat zo goed kunnen; inhoudelijk complexe onderwerpen helder en met een knipoog overbrengen op hun publiek. ",
            img_3: "/images/sirelo_4.png",
            title_3: "UX Design",
            txt_3: "Waar mijn collega’s aan de slag gingen met de brand identity zoals de huisstijl en illustraties ging ik met de marketeers van Sirelo aan de slag om de UX van het platform te optimaliseren. De grootste uitdaging was om de voor SEO en CRO geoptimaliseerde pagina’s te optimaliseren voor een goede user experience. ",
            img_4: "/images/sirelo_5.png",
         },
         Overige: {
            name: "Overige",
            desc: "Andere projecten",
            imgSrc: "/images/ducati_1.jpg",
            timeFrame: "2016 - Nu",
            workDone: "Concept & Design",
            website: "https://sirelo.nl",
            intro: "Ik heb in de afgelopen jaren als UX designer enorm veel web projecten mogen doen. Hierbij dan ook een overzicht met een aantal projecten waar ik nog net zo trots op ben.",
            img_1: "/images/hp_1.png",
            title_1: "Hygienepapier.nl",
            txt_1: "Hygienepapier.nl is 5 jaar geleden vanuit een toilethygiene b2b groothandel met Keytoe opgestart om de MKB aan te gaan spreken als goedkoopste webshop in de branche. Ik was vanaf het begin betrokken als UX designer om met een enorm aanbod een goede UX te ontwikkelen. Doorlopend testen en optimaliseren heeft gezorgd voor een explosieve groei waarmee Hygienepapier.nl nu de grootste online handelaar van de benelux is geworden. ",
            img_2: "/images/ducati_2.png",
            title_2: "Ducati Zaltbommel",
            txt_2: "Ducati Zaltbommel is een van de weinige officiële Ducati dealers van nederland. Met een prachtige showroom en uitstekende service kwam Ducati met de vraag om deze ervaring ook online tot uiting te brengen. ",
         }
      }

  export default Data